export default {
  title: "greweb.me",
  description:
    "As a generative plotter artist, I use code to generate art (creative coding) and physically create it with pen plotters, which is itself a generative process – each physical plot is a unique variant. I love dualities, like digital vs analog physical, abstract vs figurative, orthogonal vs polar, photo vs noise,...",
  thumbnail: "/logo.svg",
  photo: "/profile.jpg",
  thumbnailDomain: "http://greweb.me",
  siteDomain: "https://greweb.me",
  social: [
    {
      id: "discord",
      url: "https://discord.gg/DQBajxzn",
      icon: "/icons/discord.svg",
      text: "DISCORD",
      color: "#757ff8",
      highlighted: true,
    },
    {
      id: "twitter",
      url: "https://twitter.com/greweb",
      icon: "/icons/twitter.svg",
      text: "@greweb",
      color: "#1DA1F2",
    },
    {
      id: "instagram",
      url: "https://instagram.com/greweb",
      icon: "/icons/instagram.svg",
      text: "greweb",
      color: "#e55255",
    },
    {
      id: "twitch",
      url: "https://twitch.tv/greweb",
      icon: "/icons/twitch.svg",
      text: "greweb",
      color: "#6441a5",
    },
    {
      id: "youtube",
      url: "https://youtube.com/@greweb",
      icon: "/icons/youtube.svg",
      text: "youtube",
      color: "#ff0000",
    },
    {
      id: "github",
      url: "https://github.com/gre",
      icon: "/icons/github.svg",
      text: "gre",
      color: "#000",
    },
    {
      id: "opensea",
      url: "https://opensea.io/greweb?tab=created",
      icon: "/icons/eth.svg",
      text: "greweb.eth",
      color: "#2181e2",
    },
    /*
    {
      id: "objkt",
      url: "https://objkt.com/profile/tz1cgQAQfECg5bPASYTMyJ9QJQjSUi8rfL67",
      icon: "/icons/tz.svg",
      text: "greweb.tez",
    },
    */
    {
      id: "fxhash",
      url: "https://fxhash.xyz/u/greweb",
      icon: "/icons/tz.svg",
      text: "fxhash.xyz/u/greweb",
      extra: true,
      color: "#1e51e7",
    },
    {
      id: "itch.io",
      url: "https://greweb.itch.io",
      icon: "/icons/iconmonstr-gamepad-3.svg",
      text: "greweb.itch.io",
      extra: true,
      color: "#f35a59",
    },
  ],
};
