name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          export NODE_ENV=production
          yarn add -D webpack-cli
          yarn
          yarn build-blockstyle
          yarn build
          yarn next export
          echo greweb.me > ./out/CNAME
      - name: Deploy GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
