name: "lookup test"
on:
  workflow_dispatch:
    inputs:
      value:
        description: "value"
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          T: ${{format("secrets.TEST{0}", github.event.inputs.value)}}
        run: echo $T
