name: "lookup test"
on:
  workflow_dispatch:
    inputs:
      value:
        description: "value"
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: set envs
        env:
          VALUE: ${{ github.event.inputs.value }}
          SECRETS: ${{ secrets }}
        run: |
         node -e "console.log('export T=\"'+JSON.parse(process.env.SECRETS)['TEST'+process.env.VALUE]+'\"')" > env.sh
      - name: test
        run: . env.sh; echo $T
